public interface PositionConstants {
    int NORTH_SERVE_DEUCE_X = 131;
    int NORTH_SERVE_DEUCE_Y = 79;
    int NORTH_SERVE_AD_X = 368;
    int NORTH_SERVE_AD_Y = 79;
    int NORTH_RECEIVE_DEUCE_X = 143;
    int NORTH_RECEIVE_DEUCE_Y = 106;
    int NORTH_RECEIVE_AD_X = 356;
    int NORTH_RECEIVE_AD_Y = 106;
    int SOUTH_SERVE_DEUCE_X = 368;
    int SOUTH_SERVE_DEUCE_Y = 620;
    int SOUTH_SERVE_AD_X = 131;
    int SOUTH_SERVE_AD_Y = 620;
    int SOUTH_RECEIVE_DEUCE_X = 356;
    int SOUTH_RECEIVE_DEUCE_Y = 593;
    int SOUTH_RECEIVE_AD_X = 143;
    int SOUTH_RECEIVE_AD_Y = 593;
    int NEUTRAL_X = 249;
    int NORTH_NEUTRAL_Y = 102;
    int SOUTH_NEUTRAL_Y = 597;

    int NORTH_Y_TARGET_LOWER_BOUND = 96;
    int SOUTH_Y_TARGET_LOWER_BOUND = 416;
    int Y_TARGET_RANGE = 188;
    int X_TARGET_LOWER_BOUND = 114;
    int X_TARGET_UPPER_BOUND = 385;

    int NORTH_Y_TARGET_LOWER_BOUND_SERVE = 222;
    int SOUTH_Y_TARGET_LOWER_BOUND_SERVE = 415;
    int Y_TARGET_RANGE_SERVE = 63;
    int NORTH_DEUCE_X_TARGET_LOWER_BOUND_SERVE = 114;
    int SOUTH_DEUCE_X_TARGET_LOWER_BOUND_SERVE = 252;
    int NORTH_AD_X_TARGET_LOWER_BOUND_SERVE = 252;
    int SOUTH_AD_X_TARGET_LOWER_BOUND_SERVE = 114;
    int X_TARGET_RANGE_SERVE = 134;
}
