public interface PositionConstants {
    int EAST_SERVE_DEUCE_X = 722;
    int EAST_SERVE_DEUCE_Y = 119;
    int EAST_SERVE_AD_X = 722;
    int EAST_SERVE_AD_Y = 380;
    int EAST_RECEIVE_DEUCE_X = 693;
    int EAST_RECEIVE_DEUCE_Y = 128;
    int EAST_RECEIVE_AD_X = 693;
    int EAST_RECEIVE_AD_Y = 371;
    int WEST_SERVE_DEUCE_X = 177;
    int WEST_SERVE_DEUCE_Y = 380;
    int WEST_SERVE_AD_X = 177;
    int WEST_SERVE_AD_Y = 119;
    int WEST_RECEIVE_DEUCE_X = 206;
    int WEST_RECEIVE_DEUCE_Y = 371;
    int WEST_RECEIVE_AD_X = 206;
    int WEST_RECEIVE_AD_Y = 128;
    int NEUTRAL_Y = 249;
    int EAST_NEUTRAL_X = 695;
    int WEST_NEUTRAL_X = 204;

    int EAST_X_TARGET_LOWER_BOUND = 525;
    int WEST_X_TARGET_LOWER_BOUND = 196;
    int X_TARGET_RANGE = 179;
    int Y_TARGET_LOWER_BOUND = 114;
    int Y_TARGET_UPPER_BOUND = 385;

    int EAST_X_TARGET_LOWER_BOUND_SERVE = 496;
    int WEST_X_TARGET_LOWER_BOUND_SERVE = 322;
    int Y_TARGET_RANGE_SERVE = 134;
    int X_TARGET_RANGE_SERVE = 82;
    int EAST_DEUCE_Y_TARGET_LOWER_BOUND_SERVE = 114;
    int WEST_DEUCE_Y_TARGET_LOWER_BOUND_SERVE = 252;
    int EAST_AD_Y_TARGET_LOWER_BOUND_SERVE = 252;
    int WEST_AD_Y_TARGET_LOWER_BOUND_SERVE = 114;
}
